In [1]:
from jupyterthemes import jtplot
jtplot.style("chesterish")

In [2]:
import pandas as pd

In [3]:
fruit_data = pd.read_excel("food_data.xlsx", index_col=0)

In [4]:
fruit_data.head()

,Shrt_Desc,Water_(g),Energ_Kcal,Protein_(g),Lipid_Tot_(g),Ash_(g),Carbohydrt_(g),Fiber_TD_(g),Sugar_Tot_(g),Calcium_(mg),...,Vit_K_(µg),FA_Sat_(g),FA_Mono_(g),FA_Poly_(g),Cholestrl_(mg),GmWt_1,GmWt_Desc1,GmWt_2,GmWt_Desc2,Refuse_Pct
NDB_No,,,,,,,,,,,,,,,,,,,,,
1001,"BUTTER,WITH SALT",15.87,717,0.85,81.11,2.11,0.06,0.0,0.06,24.0,...,7.0,51.368,21.021,3.043,215.0,5.00,"1 pat, (1"" sq, 1/3"" high)",14.2,1 tbsp,0.0
1002,"BUTTER,WHIPPED,W/ SALT",16.72,718,0.49,78.30,1.62,2.87,0.0,0.06,23.0,...,4.6,45.390,19.874,3.331,225.0,3.80,"1 pat, (1"" sq, 1/3"" high)",9.4,1 tbsp,0.0
1003,"BUTTER OIL,ANHYDROUS",0.24,876,0.28,99.48,0.00,0.00,0.0,0.00,4.0,...,8.6,61.924,28.732,3.694,256.0,12.80,1 tbsp,205.0,1 cup,0.0
1004,"CHEESE,BLUE",42.41,353,21.40,28.74,5.11,2.34,0.0,0.50,528.0,...,2.4,18.669,7.778,0.800,75.0,28.35,1 oz,17.0,1 cubic inch,0.0
1005,"CHEESE,BRICK",41.11,371,23.24,29.68,3.18,2.79,0.0,0.51,674.0,...,2.5,18.764,8.598,0.784,94.0,132.00,"1 cup, diced",113.0,"1 cup, shredded",0.0

In [5]:
fruit_data.tail()

,Shrt_Desc,Water_(g),Energ_Kcal,Protein_(g),Lipid_Tot_(g),Ash_(g),Carbohydrt_(g),Fiber_TD_(g),Sugar_Tot_(g),Calcium_(mg),...,Vit_K_(µg),FA_Sat_(g),FA_Mono_(g),FA_Poly_(g),Cholestrl_(mg),GmWt_1,GmWt_Desc1,GmWt_2,GmWt_Desc2,Refuse_Pct
NDB_No,,,,,,,,,,,,,,,,,,,,,
83110,"MACKEREL,SALTED",43.00,305,18.50,25.10,13.40,0.00,0.0,0.0,66.0,...,7.8,7.148,8.320,6.210,95.0,80.0,"1 piece, (5-1/2"" x 1-1/2"" x 1/2"")",17.0,"1 cubic inch, boneless",0.0
90240,"SCALLOP,(BAY&SEA),CKD,STMD",70.25,111,20.54,0.84,2.97,5.41,0.0,0.0,10.0,...,0.0,0.218,0.082,0.222,41.0,85.0,3 oz,NaN,NaN,0.0
90480,"SYRUP,CANE",26.00,269,0.00,0.00,0.86,73.14,0.0,73.2,13.0,...,0.0,0.000,0.000,0.000,0.0,21.0,1 serving,NaN,NaN,0.0
90560,"SNAIL,RAW",79.20,90,16.10,1.40,1.30,2.00,0.0,0.0,10.0,...,0.1,0.361,0.259,0.252,50.0,85.0,3 oz,NaN,NaN,0.0
93600,"TURTLE,GREEN,RAW",78.50,89,19.80,0.50,1.20,0.00,0.0,0.0,118.0,...,0.1,0.127,0.088,0.170,50.0,85.0,3 oz,NaN,NaN,0.0

In [37]:
fruit_data["Shrt_Desc"].to_list()[0]

'BUTTER,WITH SALT'

In [56]:
merged_fruit_data = fruit_data.copy()
i = 0
for fruit in fruit_data.iloc[:,0]:
    stripped_name = fruit.split(",")[0]
    merged_fruit_data["Shrt_Desc"].iloc[i] = stripped_name
    i += 1

In [57]:
merged_fruit_data.head()

,Shrt_Desc,Water_(g),Energ_Kcal,Protein_(g),Lipid_Tot_(g),Ash_(g),Carbohydrt_(g),Fiber_TD_(g),Sugar_Tot_(g),Calcium_(mg),...,Vit_K_(µg),FA_Sat_(g),FA_Mono_(g),FA_Poly_(g),Cholestrl_(mg),GmWt_1,GmWt_Desc1,GmWt_2,GmWt_Desc2,Refuse_Pct
NDB_No,,,,,,,,,,,,,,,,,,,,,
1001,BUTTER,15.87,717,0.85,81.11,2.11,0.06,0.0,0.06,24.0,...,7.0,51.368,21.021,3.043,215.0,5.00,"1 pat, (1"" sq, 1/3"" high)",14.2,1 tbsp,0.0
1002,BUTTER,16.72,718,0.49,78.30,1.62,2.87,0.0,0.06,23.0,...,4.6,45.390,19.874,3.331,225.0,3.80,"1 pat, (1"" sq, 1/3"" high)",9.4,1 tbsp,0.0
1003,BUTTER OIL,0.24,876,0.28,99.48,0.00,0.00,0.0,0.00,4.0,...,8.6,61.924,28.732,3.694,256.0,12.80,1 tbsp,205.0,1 cup,0.0
1004,CHEESE,42.41,353,21.40,28.74,5.11,2.34,0.0,0.50,528.0,...,2.4,18.669,7.778,0.800,75.0,28.35,1 oz,17.0,1 cubic inch,0.0
1005,CHEESE,41.11,371,23.24,29.68,3.18,2.79,0.0,0.51,674.0,...,2.5,18.764,8.598,0.784,94.0,132.00,"1 cup, diced",113.0,"1 cup, shredded",0.0

In [58]:
fruit_data.head()

,Shrt_Desc,Water_(g),Energ_Kcal,Protein_(g),Lipid_Tot_(g),Ash_(g),Carbohydrt_(g),Fiber_TD_(g),Sugar_Tot_(g),Calcium_(mg),...,Vit_K_(µg),FA_Sat_(g),FA_Mono_(g),FA_Poly_(g),Cholestrl_(mg),GmWt_1,GmWt_Desc1,GmWt_2,GmWt_Desc2,Refuse_Pct
NDB_No,,,,,,,,,,,,,,,,,,,,,
1001,"BUTTER,WITH SALT",15.87,717,0.85,81.11,2.11,0.06,0.0,0.06,24.0,...,7.0,51.368,21.021,3.043,215.0,5.00,"1 pat, (1"" sq, 1/3"" high)",14.2,1 tbsp,0.0
1002,"BUTTER,WHIPPED,W/ SALT",16.72,718,0.49,78.30,1.62,2.87,0.0,0.06,23.0,...,4.6,45.390,19.874,3.331,225.0,3.80,"1 pat, (1"" sq, 1/3"" high)",9.4,1 tbsp,0.0
1003,"BUTTER OIL,ANHYDROUS",0.24,876,0.28,99.48,0.00,0.00,0.0,0.00,4.0,...,8.6,61.924,28.732,3.694,256.0,12.80,1 tbsp,205.0,1 cup,0.0
1004,"CHEESE,BLUE",42.41,353,21.40,28.74,5.11,2.34,0.0,0.50,528.0,...,2.4,18.669,7.778,0.800,75.0,28.35,1 oz,17.0,1 cubic inch,0.0
1005,"CHEESE,BRICK",41.11,371,23.24,29.68,3.18,2.79,0.0,0.51,674.0,...,2.5,18.764,8.598,0.784,94.0,132.00,"1 cup, diced",113.0,"1 cup, shredded",0.0

In [69]:
merged_fruit_data["Shrt_Desc"].value_counts()

BEEF                                                  929
PORK                                                  322
LAMB                                                  295
CEREALS RTE                                           258
BEVERAGES                                             247
                                                     ...
SAUSAGE  TURKEY  BRKFST LINKS  MILD                     1
REDDI WIP FAT FREE WHIPPED TOPPING                      1
MORNINGSTAR FARMS GRILLERS BRGR STYL RECIPE CRMBL       1
CHEESE FOOD                                             1
CAMPBELL'S HOMESTYLE LT ITALIAN-STYLE WEDDING SOUP      1
Name: Shrt_Desc, Length: 1392, dtype: int64

In [77]:
merged_fruit_data.agg(["mean"])

,Water_(g),Energ_Kcal,Protein_(g),Lipid_Tot_(g),Ash_(g),Carbohydrt_(g),Fiber_TD_(g),Sugar_Tot_(g),Calcium_(mg),Iron_(mg),...,Vit_D_µg,Vit_D_IU,Vit_K_(µg),FA_Sat_(g),FA_Mono_(g),FA_Poly_(g),Cholestrl_(mg),GmWt_1,GmWt_2,Refuse_Pct
mean,54.112218,226.317634,11.342849,10.553725,1.783468,22.12771,2.187445,8.543066,76.738214,2.699674,...,0.579269,22.990142,15.631586,3.576334,4.081006,2.288767,40.613246,96.39513,250.747668,4.964416

In [81]:
agg_data = merged_fruit_data.groupby("Shrt_Desc").agg("mean")

In [94]:
agg_data.head()

,Water_(g),Energ_Kcal,Protein_(g),Lipid_Tot_(g),Ash_(g),Carbohydrt_(g),Fiber_TD_(g),Sugar_Tot_(g),Calcium_(mg),Iron_(mg),...,Vit_D_µg,Vit_D_IU,Vit_K_(µg),FA_Sat_(g),FA_Mono_(g),FA_Poly_(g),Cholestrl_(mg),GmWt_1,GmWt_2,Refuse_Pct
Shrt_Desc,,,,,,,,,,,,,,,,,,,,,
ABALONE,67.33,147.0,18.365,3.77,1.67,8.53,0.0,0.00,34.0,3.495,...,0.0,0.0,23.0,0.8975,1.424,0.890,89.5,85.00,NaN,0.0
ABIYUCH,79.90,69.0,1.500,0.10,0.90,17.60,5.3,8.55,8.0,1.610,...,NaN,NaN,NaN,0.0140,NaN,NaN,NaN,114.00,NaN,NaN
ACEROLA,91.41,32.0,0.400,0.30,0.20,7.69,1.1,NaN,12.0,0.200,...,NaN,NaN,NaN,0.0680,0.082,0.090,0.0,98.00,4.8,20.0
ACEROLA JUICE,94.30,23.0,0.400,0.30,0.20,4.80,0.3,4.50,10.0,0.500,...,NaN,NaN,1.4,0.0680,0.082,0.090,0.0,242.00,30.2,0.0
ACORN FLOUR,6.00,501.0,7.490,30.17,1.69,54.65,NaN,NaN,43.0,1.210,...,NaN,NaN,NaN,3.9230,19.110,5.813,0.0,28.35,NaN,0.0